
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
# command to install dependencies
install:
  - cp pyfaast/tests/test.ini.sample pyfaast/tests/test.ini
  - pip install -e .
  - pip install nose vcrpy flake8
script: nosetests
before_script: flake8 pyfaast